spring:
  applicaton:
    name: finex-trade
    url: jdbc:postgresql://finex-database.xxxxxxx.us-east-2.rds.amazonaws.com/finex
    username: <postgres username>
    password: <postgres password>
  jpa:
    generate: true
    properties:
      hibernate:
        jdbc:
          non_contextual_creation: true
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect

server:
  port: 8080


